// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video_report.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetVideoReportRequest struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoReportRequest) Reset()         { *m = GetVideoReportRequest{} }
func (m *GetVideoReportRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoReportRequest) ProtoMessage()    {}
func (*GetVideoReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3161dc4501f6ab5c, []int{0}
}

func (m *GetVideoReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoReportRequest.Unmarshal(m, b)
}
func (m *GetVideoReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoReportRequest.Marshal(b, m, deterministic)
}
func (m *GetVideoReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoReportRequest.Merge(m, src)
}
func (m *GetVideoReportRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoReportRequest.Size(m)
}
func (m *GetVideoReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoReportRequest proto.InternalMessageInfo

func (m *GetVideoReportRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type VideoItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ViewCount            int64    `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoItem) Reset()         { *m = VideoItem{} }
func (m *VideoItem) String() string { return proto.CompactTextString(m) }
func (*VideoItem) ProtoMessage()    {}
func (*VideoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_3161dc4501f6ab5c, []int{1}
}

func (m *VideoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoItem.Unmarshal(m, b)
}
func (m *VideoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoItem.Marshal(b, m, deterministic)
}
func (m *VideoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoItem.Merge(m, src)
}
func (m *VideoItem) XXX_Size() int {
	return xxx_messageInfo_VideoItem.Size(m)
}
func (m *VideoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoItem.DiscardUnknown(m)
}

var xxx_messageInfo_VideoItem proto.InternalMessageInfo

func (m *VideoItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VideoItem) GetViewCount() int64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

type GetVideoReportResponse struct {
	Reply                []*VideoItem `protobuf:"bytes,1,rep,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetVideoReportResponse) Reset()         { *m = GetVideoReportResponse{} }
func (m *GetVideoReportResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideoReportResponse) ProtoMessage()    {}
func (*GetVideoReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3161dc4501f6ab5c, []int{2}
}

func (m *GetVideoReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoReportResponse.Unmarshal(m, b)
}
func (m *GetVideoReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoReportResponse.Marshal(b, m, deterministic)
}
func (m *GetVideoReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoReportResponse.Merge(m, src)
}
func (m *GetVideoReportResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideoReportResponse.Size(m)
}
func (m *GetVideoReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoReportResponse proto.InternalMessageInfo

func (m *GetVideoReportResponse) GetReply() []*VideoItem {
	if m != nil {
		return m.Reply
	}
	return nil
}

func init() {
	proto.RegisterType((*GetVideoReportRequest)(nil), "proto.GetVideoReportRequest")
	proto.RegisterType((*VideoItem)(nil), "proto.VideoItem")
	proto.RegisterType((*GetVideoReportResponse)(nil), "proto.GetVideoReportResponse")
}

func init() { proto.RegisterFile("video_report.proto", fileDescriptor_3161dc4501f6ab5c) }

var fileDescriptor_3161dc4501f6ab5c = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xcb, 0x4c, 0x49,
	0xcd, 0x8f, 0x2f, 0x4a, 0x2d, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x53, 0x4a, 0xea, 0x5c, 0xa2, 0xee, 0xa9, 0x25, 0x61, 0x20, 0xf9, 0x20, 0xb0, 0x74, 0x50,
	0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x15, 0x17, 0x27, 0x58, 0x95, 0x67, 0x49, 0x6a, 0x2e,
	0x5c, 0x92, 0x11, 0x22, 0x29, 0x24, 0xcb, 0xc5, 0x55, 0x96, 0x99, 0x5a, 0x1e, 0x9f, 0x9c, 0x5f,
	0x9a, 0x57, 0x22, 0xc1, 0x04, 0x16, 0xe7, 0x04, 0x89, 0x38, 0x83, 0x04, 0x94, 0x1c, 0xb8, 0xc4,
	0xd0, 0x2d, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe3, 0x62, 0x2d, 0x4a, 0x2d, 0xc8,
	0xa9, 0x04, 0x5b, 0xc4, 0x6d, 0x24, 0x00, 0x71, 0x9c, 0x1e, 0xdc, 0xa6, 0x20, 0x88, 0xb4, 0x51,
	0x12, 0x17, 0x2f, 0x44, 0x67, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x20, 0x97, 0x10,
	0xcc, 0xc8, 0xe2, 0x30, 0x98, 0x45, 0x42, 0x32, 0x50, 0xfd, 0x58, 0xbd, 0x24, 0x25, 0x8b, 0x43,
	0x16, 0xe2, 0x96, 0x24, 0x36, 0xb0, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xf0, 0x12,
	0x49, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetVideosViewCount(ctx context.Context, in *GetVideoReportRequest, opts ...grpc.CallOption) (*GetVideoReportResponse, error)
}

type reportServiceClient struct {
	cc *grpc.ClientConn
}

func NewReportServiceClient(cc *grpc.ClientConn) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetVideosViewCount(ctx context.Context, in *GetVideoReportRequest, opts ...grpc.CallOption) (*GetVideoReportResponse, error) {
	out := new(GetVideoReportResponse)
	err := c.cc.Invoke(ctx, "/proto.ReportService/GetVideosViewCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
type ReportServiceServer interface {
	GetVideosViewCount(context.Context, *GetVideoReportRequest) (*GetVideoReportResponse, error)
}

// UnimplementedReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (*UnimplementedReportServiceServer) GetVideosViewCount(ctx context.Context, req *GetVideoReportRequest) (*GetVideoReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideosViewCount not implemented")
}

func RegisterReportServiceServer(s *grpc.Server, srv ReportServiceServer) {
	s.RegisterService(&_ReportService_serviceDesc, srv)
}

func _ReportService_GetVideosViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetVideosViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ReportService/GetVideosViewCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetVideosViewCount(ctx, req.(*GetVideoReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideosViewCount",
			Handler:    _ReportService_GetVideosViewCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video_report.proto",
}
